import { useState } from "react";
import { Settings, Zap, ShieldAlert } from "lucide-react";
import { api } from "../../services/api";
import { toast } from "sonner";

export function AdminSystem() {
  const [multiplier, setMultiplier] = useState(1);

  const applyOverclock = async (val: number) => {
    try {
      await api.post("/api/admin/overclock", { multiplier: val });
      setMultiplier(val);
      toast.success(`System multiplier set to ${val}X`);
    } catch (e) {
      toast.error("Failed to reach server");
    }
  };

  return (
    <div className="space-y-8 max-w-4xl">
      <h1 className="text-3xl font-bold text-red-500 uppercase tracking-widest border-b border-border pb-4 flex items-center gap-4">
        <Settings className="w-8 h-8" /> Game Systems & Anomalies
      </h1>

      <div className="bg-black/50 border border-border p-6">
        <h2 className="text-lg font-bold text-gold uppercase mb-4 flex items-center gap-2">
          <Zap className="w-6 h-6 text-blue-400" /> Global Overclock (Score
          Multiplier)
        </h2>
        <p className="text-muted text-sm mb-6">
          Multiply all point yields generated by operative solves. Triggers a
          live broadcast to all active connections.
        </p>

        <div className="flex gap-4">
          <button
            onClick={() => applyOverclock(1)}
            className={`px-8 py-3 font-bold uppercase transition border ${multiplier === 1 ? "bg-blue-600 text-white border-blue-500" : "bg-black text-muted hover:border-blue-500"}`}
          >
            1X (Standard)
          </button>
          <button
            onClick={() => applyOverclock(2)}
            className={`px-8 py-3 font-bold uppercase transition border ${multiplier === 2 ? "bg-gold text-black border-gold shadow-[0_0_15px_rgba(212,160,23,0.3)]" : "bg-black text-muted hover:border-gold"}`}
          >
            2X (Overclock)
          </button>
          <button
            onClick={() => applyOverclock(3)}
            className={`px-8 py-3 font-bold uppercase transition border ${multiplier === 3 ? "bg-red-600 text-white border-red-500 shadow-[0_0_15px_rgba(239,68,68,0.3)]" : "bg-black text-muted hover:border-red-500"}`}
          >
            3X (Critical)
          </button>
        </div>
      </div>

      <div className="bg-black/50 border border-border p-6 opacity-60">
        <h2 className="text-lg font-bold text-red-500 uppercase mb-4 flex items-center gap-2">
          <ShieldAlert className="w-6 h-6 text-red-500" /> Anti-Bruteforce
          Module
        </h2>
        <p className="text-muted text-sm mb-4">
          Automatically issues a 60-second client lockdown on any team that
          submits 3 consecutive failed queries anywhere across the system.
        </p>
        <p className="text-green-500 font-mono text-sm">
          [STATUS: ONLINE & ENFORCED SYSTEM-WIDE]
        </p>
      </div>
    </div>
  );
}
