import { useState, useEffect } from "react";
import { Settings, Zap, ShieldAlert } from "lucide-react";
import { api } from "../../services/api";
import { toast } from "sonner";

export function AdminSystem() {
  const [multiplier, setMultiplier] = useState(1);
  const [isLockdownEnabled, setIsLockdownEnabled] = useState(false);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchStatus = async () => {
      try {
        const d = await api.get<any>("/api/admin/lockdown/status");
        setIsLockdownEnabled(d.isLockdownEnabled);
      } catch (e) {
        console.error(e);
      } finally {
        setLoading(false);
      }
    };
    fetchStatus();
  }, []);

  const toggleLockdown = async () => {
    try {
      const d = await api.post<any>("/api/admin/lockdown/toggle", { enabled: !isLockdownEnabled });
      setIsLockdownEnabled(d.isLockdownEnabled);
      toast.success(`Security Lockdown System ${d.isLockdownEnabled ? 'ENABLED' : 'DISABLED'}`);
    } catch (e) {
      toast.error("Failed to toggle lockdown");
    }
  };

  const applyOverclock = async (val: number) => {
    try {
      await api.post("/api/admin/overclock", { multiplier: val });
      setMultiplier(val);
      toast.success(`System multiplier set to ${val}X`);
    } catch (e) {
      toast.error("Failed to reach server");
    }
  };

  return (
    <div className="space-y-8 max-w-4xl">
      <h1 className="text-3xl font-bold text-red-500 uppercase tracking-widest border-b border-border pb-4 flex items-center gap-4">
        <Settings className="w-8 h-8" /> Game Systems & Anomalies
      </h1>

      <div className="bg-black/50 border border-border p-6">
        <h2 className="text-lg font-bold text-gold uppercase mb-4 flex items-center gap-2">
          <Zap className="w-6 h-6 text-blue-400" /> Global Overclock (Score
          Multiplier)
        </h2>
        <p className="text-muted text-sm mb-6">
          Multiply all point yields generated by operative solves. Triggers a
          live broadcast to all active connections.
        </p>

        <div className="flex gap-4">
          <button
            onClick={() => applyOverclock(1)}
            className={`px-8 py-3 font-bold uppercase transition border ${multiplier === 1 ? "bg-blue-600 text-white border-blue-500" : "bg-black text-muted hover:border-blue-500"}`}
          >
            1X (Standard)
          </button>
          <button
            onClick={() => applyOverclock(2)}
            className={`px-8 py-3 font-bold uppercase transition border ${multiplier === 2 ? "bg-gold text-black border-gold shadow-[0_0_15px_rgba(212,160,23,0.3)]" : "bg-black text-muted hover:border-gold"}`}
          >
            2X (Overclock)
          </button>
          <button
            onClick={() => applyOverclock(3)}
            className={`px-8 py-3 font-bold uppercase transition border ${multiplier === 3 ? "bg-red-600 text-white border-red-500 shadow-[0_0_15px_rgba(239,68,68,0.3)]" : "bg-black text-muted hover:border-red-500"}`}
          >
            3X (Critical)
          </button>
        </div>
      </div>

      <div className={`bg-black/50 border p-6 transition-all ${isLockdownEnabled ? 'border-red-500 shadow-[0_0_15px_rgba(239,68,68,0.2)]' : 'border-border opacity-60'}`}>
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-lg font-bold text-red-500 uppercase flex items-center gap-2">
            <ShieldAlert className="w-6 h-6 text-red-500" /> Anti-Bruteforce
            Module
          </h2>
          <button
            onClick={toggleLockdown}
            disabled={loading}
            className={`px-6 py-2 font-bold uppercase text-xs border transition-all ${isLockdownEnabled ? 'bg-red-600 text-white border-red-500' : 'bg-black text-muted border-border hover:text-white'}`}
          >
            {isLockdownEnabled ? 'Deactivate System' : 'Activate System'}
          </button>
        </div>
        <p className="text-muted text-sm mb-4">
          Automatically issues a 60-second client lockdown on any team that
          submits 3 consecutive failed queries anywhere across the system.
        </p>
        <p className={`font-mono text-sm ${isLockdownEnabled ? 'text-red-500 animate-pulse' : 'text-muted'}`}>
          [STATUS: {isLockdownEnabled ? 'ONLINE & ENFORCED SYSTEM-WIDE' : 'OFFLINE - MONITORING ONLY'}]
        </p>
      </div>
    </div>
  );
}
